language: cpp
compiler:
  - gcc
before_script:
  - cd ..
  - git clone https://github.com/zeehio/speech-tools.git speech_tools
  - cd speech_tools
  - ./configure && make
  - cd ../festvox
script:
  - ./configure && make

